### ISSUE TITLE
Белая книга

### ISSUE THREAD

**Issue by ghost** [swordofwolf/OPTRepos#1]
Пилим описание языка

**Comment by ghost** [comment]
Нам нужно: 
1) Общие описание языка (что-то вроде этого есть)
2) описание конструкций (циклы, условные операторы, ретурны, свич кейсы и т.д.)
3) описание структур данных (структуры не структуры)
4) описание операторов. Какие есть, какие приоритеты, над какими типами выполняются
5) соответственно определится с типизацией
6) наименование переменных и литералов

Берем, пилим, радуемся жизни.
Вот вам еще позитивную картинку для повышение производительности
![image](https://cloud.githubusercontent.com/assets/10672976/6392068/4c31599a-bdef-11e4-9db3-a034a17a90a6.png)

**Comment by ghost** [comment]
Отлично сработано!

**Comment by swordofwolf** [comment]
<iframe src="//coub.com/embed/ak2m?muted=false&autostart=false&originalSize=false&hideTopBar=false&startWithHD=false" allowfullscreen="true" frameborder="0" width="640" height="270"></iframe>

**Comment by swordofwolf** [comment]
http://coub.com/view/ak2m
